'use strict';

const fs = require('fs');
const path = require('path');

// $VAR_NAME in an arg = resolve from process.env at MCP server startup (wrapper script)
// {{VAR_NAME}} in an arg = resolve at activation time (build-time placeholder)
const RUNTIME_ENV_RE = /^\$([A-Z0-9_]+)$/;

function resolvePlaceholders(obj, vars) {
  if (typeof obj === 'string') {
    return obj.replace(/\{\{([A-Z0-9_]+)\}\}/g, (_, key) =>
      vars[key] !== undefined ? vars[key] : `{{${key}}}`
    );
  }
  if (Array.isArray(obj)) return obj.map(v => resolvePlaceholders(v, vars));
  if (obj && typeof obj === 'object') {
    return Object.fromEntries(
      Object.entries(obj).map(([k, v]) => [k, resolvePlaceholders(v, vars)])
    );
  }
  return obj;
}

function hasUnresolved(obj) {
  return /\{\{[A-Z0-9_]+\}\}/.test(JSON.stringify(obj));
}

/**
 * Generates a zero-secret Node.js wrapper that resolves $VAR_NAME args from
 * process.env at MCP server startup. The wrapper is written to claudeDir/mcp/<name>.js.
 * Nothing sensitive is written to settings.json.
 */
function sanitizeServerName(name) {
  // Allow alphanumeric, hyphens, and underscores — prevent path traversal via crafted mcp.json keys.
  // Must start with alphanumeric to avoid leading dashes/underscores.
  if (!/^[a-zA-Z0-9][a-zA-Z0-9_-]*$/.test(name)) {
    throw new Error(`Invalid MCP server name: '${name}'. Use only letters, digits, hyphens, and underscores.`);
  }
  return name;
}

function generateWrapper(claudeDir, serverName, command, args, runtimeVarNames) {
  const mcpDir = path.join(claudeDir, 'mcp');
  fs.mkdirSync(mcpDir, { recursive: true });

  const safeName = sanitizeServerName(serverName);
  const wrapperPath = path.join(mcpDir, `${safeName}.js`);

  const checks = runtimeVarNames.map(v =>
    `if (!process.env.${v}) { process.stderr.write('[forge-mcp] ${v} is not set — ${serverName} MCP server cannot start\\n'); process.exit(1); }`
  ).join('\n');

  const argExprs = args.map(arg => {
    const m = String(arg).match(RUNTIME_ENV_RE);
    return m ? `process.env.${m[1]}` : JSON.stringify(arg);
  });

  const content = `#!/usr/bin/env node
// Auto-generated by claude-chameleon — do not edit manually. Re-run /explore to regenerate.
const { spawn } = require('child_process');
${checks}
const child = spawn(${JSON.stringify(command)}, [${argExprs.join(', ')}], { stdio: 'inherit', env: process.env });
child.on('exit', code => process.exit(code ?? 0));
`;
  fs.writeFileSync(wrapperPath, content, { mode: 0o755 });
  return wrapperPath;
}

/**
 * Merges mcpServers from mcp.json into a settings object.
 *
 * - Args with $VAR_NAME: generates a wrapper script in claudeDir/mcp/<name>.js that reads
 *   env vars at runtime. settings.json points to the wrapper — no secrets on disk.
 * - Args with {{PLACEHOLDER}}: resolved at activation time (for non-sensitive values).
 *
 * Returns { settings, added: string[], skipped: {name, missing}[], warnEnv: {name, vars}[] }
 */
const ALLOWED_COMMANDS = new Set(['npx', 'node', 'bun', 'pnpm', 'uvx', 'uv', 'python', 'python3', 'yarn', 'deno']);

function mergeMcpIntoSettings(mcpJson, settings, vars, claudeDir, dryRun, profileName) {
  if (!settings.mcpServers) settings.mcpServers = {};
  const servers = mcpJson.mcpServers || {};
  const requiredEnvVars = mcpJson.env_vars || [];
  const added = [];
  const skipped = [];
  const warnEnv = [];

  // Restrict {{VAR}} substitution scope to: synthetic vars + values declared in mcp.json's
  // env_vars. This prevents a malicious mcp.json from exfiltrating arbitrary process.env
  // entries (e.g., {{GITHUB_TOKEN}}) into the on-disk settings.json.
  const placeholderVars = Object.create(null);
  if (vars && vars.PROJECT_ROOT !== undefined) placeholderVars.PROJECT_ROOT = vars.PROJECT_ROOT;
  if (vars && vars.FORGE_ROOT !== undefined) placeholderVars.FORGE_ROOT = vars.FORGE_ROOT;
  for (const declared of requiredEnvVars) {
    if (vars && vars[declared] !== undefined) placeholderVars[declared] = vars[declared];
  }

  for (const [name, config] of Object.entries(servers)) {
    // Auto-namespace on collision: "postgres" from "python-django" → "django-postgres"
    let registeredName = name;
    if (settings.mcpServers[name] && profileName) {
      const prefix = profileName.replace(/^python-/, '').replace(/^php-/, '');
      registeredName = `${prefix}-${name}`;
      process.stderr.write(`⚠ MCP server name collision: "${name}" already registered. Activating as "${registeredName}" instead.\n`);
    }

    // Command allowlist — prevents a malicious profile from spawning arbitrary binaries.
    const cmdBase = config.command ? path.basename(config.command) : '';
    if (!ALLOWED_COMMANDS.has(cmdBase)) {
      process.stderr.write(`⚠ profiles/${profileName}/mcp.json: command '${config.command}' is not in the allowed list (${[...ALLOWED_COMMANDS].join(', ')}) — skipping server '${name}'\n`);
      skipped.push({ name: registeredName, reason: 'command not allowed', missing: [] });
      continue;
    }

    const args = config.args || [];
    const runtimeVarNames = args
      .map(a => { const m = String(a).match(RUNTIME_ENV_RE); return m ? m[1] : null; })
      .filter(Boolean);

    if (runtimeVarNames.length > 0) {
      // Wrapper approach: env vars resolved at MCP startup, not here.
      // If any required env vars are missing now, skip registration entirely so we don't
      // leave a broken MCP server that errors on every Claude Code session.
      const missingNow = runtimeVarNames.filter(v => !vars[v]);
      if (missingNow.length > 0) {
        warnEnv.push({ name: registeredName, vars: missingNow });
        skipped.push({ name: registeredName, missing: missingNow });
        continue;
      }
      if (!dryRun) {
        let wrapperPath;
        try {
          wrapperPath = generateWrapper(claudeDir, registeredName, config.command, args, runtimeVarNames);
        } catch (e) {
          process.stderr.write(`⚠ Skipping MCP server "${registeredName}": ${e.message}\n`);
          skipped.push({ name: registeredName, missing: [e.message] });
          continue;
        }
        settings.mcpServers[registeredName] = { command: 'node', args: [wrapperPath] };
      }
      added.push(registeredName);
    } else {
      // Build-time resolution: {{PLACEHOLDER}} values resolved now — but only from
      // explicitly declared env_vars + synthetic vars (no process.env passthrough).
      const resolved = resolvePlaceholders(config, placeholderVars);
      if (hasUnresolved(resolved)) {
        const missing = requiredEnvVars.filter(v => !placeholderVars[v]);
        skipped.push({ name: registeredName, missing: missing.length ? missing : ['unknown'] });
      } else {
        if (!dryRun) settings.mcpServers[registeredName] = resolved;
        added.push(registeredName);
      }
    }
  }

  return { settings, added, skipped, warnEnv };
}

/**
 * Returns the list of MCP server names declared in an mcp.json.
 * If settings is provided, also includes any auto-renamed variants
 * (e.g., "django-postgres" when "postgres" collided at activation time).
 * profileName is used to compute the exact collision prefix so we don't
 * match unrelated user-owned servers that happen to share the <word>-<name> shape.
 */
function collectMcpServerNames(mcpJson, settings, profileName) {
  const originalNames = Object.keys(mcpJson.mcpServers || {});
  if (!settings || !settings.mcpServers) return originalNames;
  const registered = Object.keys(settings.mcpServers);
  // Compute the prefix used by auto-namespace logic (mirrors mergeMcpIntoSettings).
  const prefix = profileName
    ? profileName.replace(/^python-/, '').replace(/^php-/, '')
    : null;
  const result = new Set(originalNames);
  for (const original of originalNames) {
    for (const key of registered) {
      if (key === original) { result.add(key); continue; }
      // Only match the exact prefix this profile would have produced.
      if (prefix && key === `${prefix}-${original}`) { result.add(key); }
    }
  }
  return [...result];
}

/**
 * Removes named MCP servers from settings and deletes any generated wrapper scripts.
 */
function removeMcpServersFromSettings(settings, serverNames, claudeDir) {
  if (!settings.mcpServers) return settings;
  for (const name of serverNames) {
    delete settings.mcpServers[name];
    if (claudeDir) {
      try {
        const safeName = sanitizeServerName(name);
        fs.unlinkSync(path.join(claudeDir, 'mcp', `${safeName}.js`));
      } catch {}
    }
  }
  // Remove empty mcp dir if we can
  if (claudeDir) {
    try { fs.rmdirSync(path.join(claudeDir, 'mcp')); } catch {}
  }
  if (Object.keys(settings.mcpServers).length === 0) delete settings.mcpServers;
  return settings;
}

/**
 * Reads KEY=VALUE pairs from <projectPath>/.env.
 * Falls back to process.env so CI env vars work without a .env file.
 */
function parseEnvFile(projectPath) {
  const vars = Object.assign({}, process.env);
  try {
    const content = fs.readFileSync(path.join(projectPath, '.env'), 'utf8');
    for (const line of content.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eqIdx = trimmed.indexOf('=');
      if (eqIdx < 0) continue;
      const key = trimmed.slice(0, eqIdx).trim();
      const val = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '');
      vars[key] = val;
    }
  } catch {}
  return vars;
}

module.exports = {
  mergeMcpIntoSettings,
  collectMcpServerNames,
  removeMcpServersFromSettings,
  parseEnvFile,
};
