'use strict';

// Parses .forge.yaml (not frontmatter). Handles inline arrays at depth 4.
function parseSimpleYaml(content) {
  if (!content || !content.trim()) return Object.create(null);
  const result = Object.create(null);
  const lines = content.split('\n').filter(l => !l.trim().startsWith('#') && l.trim());
  let currentKey = null;
  let currentList = null;
  let currentObj = null;

  for (const line of lines) {
    const indent = line.length - line.trimStart().length;
    const trimmed = line.trimStart();

    if (indent === 0 && trimmed.includes(':')) {
      const colonIdx = trimmed.indexOf(':');
      currentKey = trimmed.slice(0, colonIdx).trim();
      const v = trimmed.slice(colonIdx + 1).trim();
      if (v === '') {
        result[currentKey] = [];
        currentList = result[currentKey];
        currentObj = null;
      } else {
        result[currentKey] = v.replace(/^["']|["']$/g, '');
        currentList = null;
      }
      continue;
    }

    if (indent === 2 && trimmed.startsWith('- ')) {
      const itemRaw = trimmed.slice(2);
      if (itemRaw.includes(':')) {
        currentObj = Object.create(null);
        if (currentList) currentList.push(currentObj);
        const colonIdx = itemRaw.indexOf(':');
        const k = itemRaw.slice(0, colonIdx).trim();
        const v = itemRaw.slice(colonIdx + 1).trim().replace(/^["']|["']$/g, '');
        if (v) currentObj[k] = v;
      } else {
        currentObj = null;
        if (currentList) currentList.push(itemRaw.trim().replace(/^["']|["']$/g, ''));
      }
      continue;
    }

    if (indent === 4 && currentObj) {
      const colonIdx = trimmed.indexOf(':');
      if (colonIdx > 0) {
        const k = trimmed.slice(0, colonIdx).trim();
        const rawVal = trimmed.slice(colonIdx + 1).trim();
        if (rawVal.startsWith('[')) {
          currentObj[k] = rawVal.slice(1, -1).split(',').map(s => s.trim().replace(/^["']|["']$/g, ''));
        } else {
          currentObj[k] = rawVal.replace(/^["']|["']$/g, '');
        }
      }
    }
  }

  const hasContentLines = content.split('\n').some(l => { const t = l.trim(); return t && !t.startsWith('#'); });
  if (hasContentLines && Object.keys(result).length === 0) {
    process.stderr.write('⚠ YAML parse produced empty result — check file format\n');
  }
  return result;
}

function writeGlobalForgeYaml(forgeRoot, forgeVersion = '1.0.0') {
  return `# claude-chameleon global config — machine-specific, do not commit\nforge_version: "${forgeVersion}"\nforge_root: "${forgeRoot}"\n`;
}

function writeProjectForgeYaml(profileNames, forgeVersion = '1.0.0') {
  const profileLines = profileNames.map(name => `  - ${name}`).join('\n');
  return `# Generated by claude-chameleon /explore — commit this file\nforge_version: "${forgeVersion}"\nprofiles:\n${profileLines}\n`;
}

// Parses YAML frontmatter (between leading `---` markers). Coerces booleans/numbers,
// handles inline arrays, and unescapes \" / \' in quoted strings.
function parseFrontmatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return Object.create(null);
  const result = Object.create(null);
  let currentKey = null;
  let currentList = null;
  let currentObj = null;

  for (const rawLine of match[1].split('\n')) {
    const trimmed = rawLine.trimStart();
    const indent = rawLine.length - trimmed.length;

    if (indent === 0 && trimmed.includes(':') && !trimmed.startsWith('-')) {
      const colonIdx = trimmed.indexOf(':');
      currentKey = trimmed.slice(0, colonIdx).trim();
      const val = trimmed.slice(colonIdx + 1).trim();
      if (val === '') {
        result[currentKey] = []; currentList = result[currentKey]; currentObj = null;
      } else if (val === 'true') { result[currentKey] = true; currentList = null; }
      else if (val === 'false') { result[currentKey] = false; currentList = null; }
      else if (!isNaN(Number(val))) { result[currentKey] = Number(val); currentList = null; }
      else { result[currentKey] = val.replace(/^["']|["']$/g, ''); currentList = null; }
      continue;
    }

    if (indent === 2 && trimmed.startsWith('- ')) {
      const itemRaw = trimmed.slice(2).trim();
      if (itemRaw.includes(':')) {
        currentObj = Object.create(null);
        if (currentList) currentList.push(currentObj);
        const colonIdx = itemRaw.indexOf(':');
        const objKey = itemRaw.slice(0, colonIdx).trim();
        const objVal = itemRaw.slice(colonIdx + 1).trim();
        if (objVal) currentObj[objKey] = parseYamlValue(objVal);
      } else {
        currentObj = null;
        if (currentList) currentList.push(parseYamlValue(itemRaw));
      }
      continue;
    }

    if (indent === 4 && currentObj !== null) {
      const colonIdx = trimmed.indexOf(':');
      if (colonIdx > 0) {
        currentObj[trimmed.slice(0, colonIdx).trim()] = parseYamlValue(trimmed.slice(colonIdx + 1).trim());
      }
    }
  }

  return result;
}

function parseYamlValue(val) {
  if (val === 'true') return true;
  if (val === 'false') return false;
  if (!isNaN(Number(val)) && val !== '') return Number(val);
  if (val.startsWith('[') && val.endsWith(']')) {
    return val.slice(1, -1).split(',').map(s => unquoteYaml(s.trim()));
  }
  return unquoteYaml(val);
}

function unquoteYaml(s) {
  if ((s.startsWith('"') && s.endsWith('"')) || (s.startsWith("'") && s.endsWith("'"))) {
    return s.slice(1, -1).replace(/\\"/g, '"').replace(/\\'/g, "'");
  }
  return s;
}

module.exports = { parseSimpleYaml, writeGlobalForgeYaml, writeProjectForgeYaml, parseFrontmatter, parseYamlValue, unquoteYaml };
